version: '3'
services:
  monviso:
    image: monviso
    build:
      args:
        CIRCLE_BRANCH: $CIRCLE_BRANCH
        REACT_APP_GOOGLE_API_KEY: $REACT_APP_GOOGLE_API_KEY
      context: ./packages/monviso-app
    container_name: monviso-app
    ports:
      - "5000:5000"

