version: 2.1

jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run: docker-compose -f ci-tests.yml build
workflows:
  build:
    jobs:
      - build
  version: 2

